services:
  alertmanager:
    container_name: alertmanager
    image: bitnami/alertmanager:0.28.1
    restart: unless-stopped
    volumes:
      - ../../.docker/alertmanager:/etc/alertmanager/
      - ../../.data/alertmanager:/alertmanager  
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    ports:
      - "9093:9093"
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
